CHANGELOG.md, src/models/NavItemPageBlockItem.php
Edit a block which parent block is cacheable, will clear the parent cache now.
=> Clear cache for parent block

src/admin/views/page/_settings.php
Set translated label instead of hardcoded one
=> Add i18n for 'Remove Page' button

src/admin/Module.php, src/admin/importers/BlockImporter.php, src/frontend/Module.php, src/frontend/views/error/index.php
=> New importer

CHANGELOG.md, src/base/BlockInterface.php, src/base/InternalBaseBlock.php, src/base/PhpBlock.php, src/base/PhpBlockView.php, src/models/NavItemPage.php, tests/data/assets/.gitignore, tests/data/blocks/ConcretImplementationBlock.php, tests/data/blocks/UnitTestBlock.php, tests/data/configs/cms.php, tests/src/base/PhpBlockTest.php, tests/src/base/PhpBlockViewTest.php
I am not sure with `$blockObject` variable because it require `\luya\cms\base\PhpBlock` now instead of `\luya\cms\base\InternalBaseBlock`. #13
=> Issue #13 block asset cache

src/base/PhpBlock.php
=> Refactoring block cache bug

src/admin/messages/fr/cmsadmin.php
The page params doesn't displayed all and could not be saved.
=> Bug causing admin interface bug in French

CHANGELOG.md, composer.lock, src/admin/views/page/_navitem.php, src/base/BlockVariationRegister.php, src/models/NavItemPage.php, tests/src/base/BlockVariationRegisterTest.php
This closes #86 and allows you to set a default value for block variations.
=> add option to set default variation #86

src/admin/messages/en/cmsadmin.php
I am proposing these changes as they will make more sense to native English speakers.
=> Text changes

CHANGELOG.md, src/base/InternalBaseBlock.php
=> Parents dirname for block preview

src/frontend/Bootstrap.php
added error handler to render error page if it is configured in settings.
404 page was not shown when NotFoundHttpException was thrown.
404 status code is returned:
404 site is rendered without redirect:
| Is bugfix?    | yes
| Tests pass?   | n/a
| Fixed issues  | fixes #203
=> register error handler event to render 404 page

CHANGELOG.md, src/frontend/views/commands/block/create_block_view.php, tests/src/frontend/commands/BlockControllerTest.php
=> Fix wrong block definition

CHANGELOG.md, src/frontend/Module.php, src/frontend/controllers/DefaultController.php, src/menu/Item.php, tests/src/menu/ItemTest.php
A new option which allows to fully cache a page under given circumstances.
=> option for full page cache

CHANGELOG.md, src/base/PhpBlockView.php, tests/src/base/PhpBlockViewTest.php
add new getBlock() method and remove deprecated functions.
=> add get block

src/admin/messages/pt/cmsadmin.php
Added cmsadmin pt translation
Messages for portuguese speakers (readers)
=> cmsadmin-pt-translation

src/admin/messages/ru/cmsadmin.php
Some translations
| Is bugfix?    | no
=> Some translations

CHANGELOG.md, src/frontend/controllers/DefaultController.php, src/menu/Item.php, src/menu/Query.php, src/widgets/NavTree.php, tests/src/menu/QueryTest.php
=> where condition check

CHANGELOG.md, src/base/InternalBaseBlock.php, src/base/PhpBlock.php, tests/src/base/PhpBlockTest.php
=> empty module property

CHANGELOG.md, src/models/NavItemPage.php, tests/src/models/NavItemPageTest.php
=> use renderFile without app context

.travis.yml, CHANGELOG.md, composer.json, composer.lock, src/menu/Item.php, src/menu/QueryIterator.php, src/menu/QueryIteratorFilter.php, tests/CmsConsoleTestCase.php, tests/CmsNgRestTestCase.php, tests/ModelTestCase.php, tests/WebModelTestCase.php, tests/src/controllers/DefaultControllerTest.php, tests/src/menu/ItemSqliteTest.php, tests/src/menu/ItemTest.php, tests/src/menu/QuerySqliteTest.php, tests/src/widgets/LangSwitcherSqliteTest.php
+ Find descendents (childrens children ... ) items in menu
+ option to return only a column value `->all()->column('id')` an array with ids.
=> new descendents method and column option

CHANGELOG.md, src/menu/QueryIterator.php, src/menu/QueryIteratorFilter.php, tests/src/menu/QueryTest.php
allow array access for filter iterators
=> array access

CHANGELOG.md, src/admin/Module.php, src/admin/apis/AdminController.php, src/admin/apis/LogController.php, src/admin/controllers/LogController.php, src/models/Log.php, src/models/Nav.php, src/models/NavItem.php, src/models/NavItemPageBlockItem.php, tests/src/admin/apis/AdminControllerTest.php
=> new log information

CHANGELOG.md, src/admin/apis/NavItemController.php, src/base/InternalBaseBlock.php, src/frontend/blocks/HtmlBlock.php, src/frontend/blocks/ModuleBlock.php, src/models/Block.php, src/models/Log.php, src/models/Nav.php, src/models/NavContainer.php, src/models/NavItemRedirect.php
Fix a bug where a log try to find an item title which might not exist.
=> fix bug when collecting log title

CHANGELOG.md, src/frontend/base/Controller.php
=> remove canonical url on cms pages 

CHANGELOG.md, src/admin/views/page/_navitem_settings.php
=> fixed issue with cms page form

CHANGELOG.md, src/admin/views/page/_navitem_settings.php
=> fix ng-show issue

CHANGELOG.md, src/admin/apis/NavController.php, tests/src/admin/apis/NavControllerTest.php
fix issue with unknown model error.
=> fix issue with copy as template

CHANGELOG.md, src/models/NavItemModule.php, tests/src/models/NavItemModuleTest.php
Ensure correct value is returned
=> fix action decode bug

CHANGELOG.md, src/admin/messages/cn/cmsadmin.php, src/admin/messages/de/cmsadmin.php, src/admin/messages/el/cmsadmin.php, src/admin/messages/en/cmsadmin.php, src/admin/messages/es/cmsadmin.php, src/admin/messages/fa/cmsadmin.php, src/admin/messages/fr/cmsadmin.php, src/admin/messages/it/cmsadmin.php, src/admin/messages/kr/cmsadmin.php, src/admin/messages/nl/cmsadmin.php, src/admin/messages/pl/cmsadmin.php, src/admin/messages/pt/cmsadmin.php, src/admin/messages/ru/cmsadmin.php, src/admin/messages/th/cmsadmin.php, src/admin/messages/tr/cmsadmin.php, src/admin/messages/ua/cmsadmin.php, src/admin/messages/vi/cmsadmin.php
=> fix message keys

CHANGELOG.md, UPGRADE.md, src/base/BlockInterface.php, src/base/InternalBaseBlock.php, src/models/Block.php, tests/data/blocks/ConcretImplementationBlock.php, tests/src/models/BlockTest.php
new setup method which is running after creating the block object.
=> add setup method when creating block

CHANGELOG.md, src/widgets/NavTree.php, tests/src/widgets/NavTreeTest.php
=> add title content option

CHANGELOG.md, src/menu/Item.php, src/menu/Query.php, src/menu/QueryIteratorFilter.php, tests/src/menu/ItemSqliteTest.php
=> fix issue with hidden informations

CHANGELOG.md, src/frontend/messages/cn/cms.php, src/frontend/messages/de/cms.php, src/frontend/messages/el/cms.php, src/frontend/messages/en/cms.php, src/frontend/messages/es/cms.php, src/frontend/messages/fa/cms.php, src/frontend/messages/fr/cms.php, src/frontend/messages/hu/cms.php, src/frontend/messages/id/cms.php, src/frontend/messages/it/cms.php, src/frontend/messages/nl/cms.php, src/frontend/messages/pl/cms.php, src/frontend/messages/pt/cms.php, src/frontend/messages/ru/cms.php, src/frontend/messages/th/cms.php, src/frontend/messages/tr/cms.php, src/frontend/messages/ua/cms.php, src/frontend/messages/vi/cms.php, src/tags/AliasTag.php, src/tags/MenuTag.php, src/tags/PageTag.php
=> add translations for tags

CHANGELOG.md, src/frontend/Module.php, src/frontend/controllers/DefaultController.php
=> cache duration default value

src/admin/messages/fr/cmsadmin.php
Complete french translation
-
| Is bugfix?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/luyadev/luya/issues/1159
=> Complete french translation

CHANGELOG.md, src/admin/views/page/_settings.php
Add new help info from luya admin module 3.8.0
=> add help info

CHANGELOG.md, src/frontend/controllers/DefaultController.php
=> disable caching for luya toolbar

CHANGELOG.md, src/models/NavItemPage.php
Cache blocks content only for guests, not loggedin admin users.
=> cache only guests

CHANGELOG.md, src/frontend/base/Controller.php
Changed meta infos from name to property
=> change meta info

CHANGELOG.md, src/models/NavItemPageBlockItem.php, tests/src/models/NavItemPageBlockItemTest.php
=> prevent circular reference on server side

CHANGELOG.md, src/widgets/NavTree.php
=> auto enable caching for nav tree

CHANGELOG.md, src/frontend/base/Controller.php
Add new event which is only triggered when the cms content is generated.
=> new cms page render event

tests/src/admin/importers/CmslayoutImporterTest.php
=> add testcase

CHANGELOG.md, src/admin/helpers/MenuHelper.php, src/admin/views/default/index.php
=> show toggler

CHANGELOG.md, UPGRADE.md, src/helpers/Url.php, src/models/Block.php, src/models/NavItemPage.php, tests/src/models/BlockTest.php
Removed all deprecated methods.
=> removed deprecated

.codeclimate.yml, CHANGELOG.md, src/admin/apis/MenuController.php, src/admin/views/permission/index.php, src/models/Website.php, tests/src/admin/apis/MenuControllerTest.php, tests/src/admin/controllers/PermissionControllerTest.php
Page permission with website collape
Not alle container was displayed on page permissions
| Is bugfix?    | yes
| Tests pass?   | no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Page permission with website scope

CHANGELOG.md, src/admin/migrations/m210605_172811_cms_website_permissions.php, src/admin/migrations/m210708_091145_v4.php, src/models/NavItem.php, src/models/NavItemPage.php
new migrations
closes #313 
closes #279
=> version 4 migration updates

CHANGELOG.md, UPGRADE.md, src/base/InternalBaseBlock.php, src/frontend/views/commands/block/create_block.php, tests/data/blocks/PhpTestBlock.php, tests/src/frontend/commands/BlockControllerTest.php
=> change default app

src/admin/messages/bg/cmsadmin.php, src/admin/messages/cn/cmsadmin.php, src/admin/messages/de/cmsadmin.php, src/admin/messages/el/cmsadmin.php, src/admin/messages/en/cmsadmin.php, src/admin/messages/es/cmsadmin.php, src/admin/messages/fa/cmsadmin.php, src/admin/messages/fr/cmsadmin.php, src/admin/messages/hu/cmsadmin.php, src/admin/messages/id/cmsadmin.php, src/admin/messages/it/cmsadmin.php, src/admin/messages/kr/cmsadmin.php, src/admin/messages/nl/cmsadmin.php, src/admin/messages/pl/cmsadmin.php, src/admin/messages/pt/cmsadmin.php, src/admin/messages/ru/cmsadmin.php, src/admin/messages/th/cmsadmin.php, src/admin/messages/tr/cmsadmin.php, src/admin/messages/ua/cmsadmin.php, src/admin/messages/vi/cmsadmin.php, src/admin/views/page/_navitem.php
Harmonize formatting (comments, delimiters, empty lines, tabs)
=> Formatting i18n files

CHANGELOG.md, composer.json, src/admin/views/page/update.php, src/models/Log.php, src/models/NavItem.php, src/models/NavItemPageBlockItem.php
=> Log ensure block exists

CHANGELOG.md, src/frontend/Bootstrap.php, src/frontend/Module.php
Disable WebsiteBehaviorUrlRule via module property.
Performance
=> option to disable WebsiteBehaviorUrlRule

CHANGELOG.md, src/admin/Module.php, src/admin/views/default/index.php
=> Fixed misleading use of the note_add icon

composer.json, src/admin/Module.php, src/admin/messages/bg/cmsadmin.php, src/admin/messages/cn/cmsadmin.php, src/admin/messages/de/cmsadmin.php, src/admin/messages/el/cmsadmin.php, src/admin/messages/en/cmsadmin.php, src/admin/messages/es/cmsadmin.php, src/admin/messages/fa/cmsadmin.php, src/admin/messages/fr/cmsadmin.php, src/admin/messages/hu/cmsadmin.php, src/admin/messages/id/cmsadmin.php, src/admin/messages/it/cmsadmin.php, src/admin/messages/kr/cmsadmin.php, src/admin/messages/nl/cmsadmin.php, src/admin/messages/pl/cmsadmin.php, src/admin/messages/pt/cmsadmin.php, src/admin/messages/ru/cmsadmin.php, src/admin/messages/th/cmsadmin.php, src/admin/messages/tr/cmsadmin.php, src/admin/messages/ua/cmsadmin.php, src/admin/messages/vi/cmsadmin.php
Fixed missed translation of "by" in latest page updates dashboard
via new feature https://github.com/luyadev/luya-module-admin/pull/690
| Is bugfix?    | yes
| Breaks BC?    | yes
| Tests pass?   | yes
| Fixed issues  | closes #369
=> Fixed missed translation in latest page updates dashboard

CHANGELOG.md, src/Menu.php
=> missing hostname

CHANGELOG.md, src/tags/PageTag.php
add a check whether the activeLanguageItem exists or not
=> page tag check

CHANGELOG.md, src/admin/apis/NavController.php
Fixed an issue where copy of the page does not copy all languages
=> fixed language copy bug

src/menu/Item.php, src/models/Nav.php, src/models/NavItemRedirect.php, src/tags/AliasTag.php
resolve https://github.com/luyadev/luya-module-cms/issues/390
=> update src folder links

tests/data/sql/1.0.0-RC1.sql, tests/data/sql/1.0.0-beta7.sql, tests/data/sql/1.0.0-beta8.sql
resolve https://github.com/luyadev/luya-module-cms/issues/393
=> update tests folder links

CHANGELOG.md, composer.json, src/models/NavContainer.php, src/models/Website.php
=> fixed website selector in container

CHANGELOG.md, src/LinkConverter.php
php 8.1 compatibility issues under certain circumstances.
=> php 8.1 ensure string

src/menu/InjectItem.php
- Added a hint to developer like in https://github.com/luyadev/luya.io/pull/81, discussed in https://github.com/luyadev/luya-module-cms/issues/58
| Is bugfix?    | no
| Tests pass?   | yes
| Fixed issues  | Closes #58
=> Added hint regarding parent item's language for menu item injection

src/helpers/BlockHelper.php, src/models/NavItem.php
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> No filter apply
